version: '3.8'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    env_file: .env
  mongo:
    image: mongo
    ports:
      - '27017:27017'
#version: "3"
#services:
#  backend:
#    build: .
#    ports:
#      - "3000:3000"
#    environment:
#      - MONGO_URI=${MONGO_URI}
#      - PORT=3000
